create table public.owner (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  owner_id uuid null default auth.uid (),
  phone text null,
  email text null,
  firstname text null,
  lastname text null,
  address text null,
  deleted_at date null,
  marked_for_deletion boolean null,
  country_code text null,
  constraint owner_pkey primary key (id),
  constraint owner_owner_id_fkey foreign KEY (owner_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;
