create table public.pet_claims (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  owner_id uuid null default auth.uid (),
  sighting_id uuid null default gen_random_uuid (),
  pet_id uuid null default gen_random_uuid (),
  confirmed boolean null default false,
  constraint pet_claims_pkey primary key (id),
  constraint pet_claims_pet_id_fkey foreign KEY (pet_id) references pets (id) on delete CASCADE,
  constraint pet_claims_sighting_id_fkey foreign KEY (sighting_id) references sightings (id)
) TABLESPACE pg_default;

create trigger on_pet_claim_confirmed
after
update on pet_claims for EACH row
execute FUNCTION trigger_update_sightings_on_claim_confirm ();
